MAINT_METRICS = ["VOLUME", "DUPLICATION", "UNIT_SIZE", "UNIT_COMPLEXITY", "UNIT_INTERFACING", "MODULE_COUPLING",
                 "COMPONENT_INDEPENDENCE", "COMPONENT_ENTANGLEMENT"]
ARCH_METRICS = ["CODE_BREAKDOWN", "COMPONENT_COUPLING", "COMPONENT_COHESION", "CODE_REUSE",
                "COMMUNICATION_CENTRALIZATION", "DATA_COUPLING", "TECHNOLOGY_PREVALENCE", "BOUNDED_EVOLUTION",
                "KNOWLEDGE_DISTRIBUTION", "COMPONENT_FRESHNESS"]
ARCH_SUBCHARACTERISTICS = ["KNOWLEDGE", "COMMUNICATION", "DATA_ACCESS", "STRUCTURE", "EVOLUTION", "TECHNOLOGY_STACK"]
