name: report-generator-compatibility-check
on:
  push:
    paths:
      - 'report-generator/**'
  pull_request:
    paths:
      - 'report-generator/**'
jobs:
  compatibility-check:
    name: "Python compatibility check"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.13' ]
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install dependencies"
        run: |
          pip3 install -e "./report-generator/[test]"

      - name: "Check syntax and imports"
        run: |
          python -m compileall -f ./report-generator/
          cd report-generator && python -c "import report_generator; print('Import successful for Python ${{ matrix.python-version }}')"