name: unittests
on:
  pull_request:
  push:
    branches: [main]
jobs:
  unittests:
    name: "Python unit tests"
    runs-on: ubuntu-latest
    env:
      REPORT_GENERATOR_TESTS_TOKEN: ${{ secrets.SIGRID_CI_TOKEN }}
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4
        
      - name: "Install native dependencies"
        run: |
          sudo apt update
          sudo apt install -y ldap-utils slapd enchant-2 libldap2-dev libsasl2-dev apparmor-utils

      - name: "Install Python dependencies"
        run: |
          pip3 install -e "./report-generator/[test]"
          pip3 install -r ldap-group-sync/requirements.txt
      
      - name: "Report Generator tests"
        run: |
          pytest --ignore=ldap-group-sync/ --junitxml=results.xml
          
      - name: "LDAP Group Sync tests"
        run: |
          cd ldap-group-sync
          python3 -m pytest

      - name: "Upload test results"
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results.xml

      - name: "Publish test results"
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: results.xml
