name: unittests
on: [push, pull_request]
jobs:
  unittests:
    name: "Python unit tests"
    runs-on: ubuntu-latest
    env:
      REPORT_GENERATOR_TESTS_TOKEN: ${{ secrets.REPORT_GENERATOR_TESTS_TOKEN }}
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: |
          pip3 install -e "./report-generator/[test]"

      - name: "Run tests"
        run: |
          pytest --junitxml=results.xml

      - name: "Upload test results"
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results.xml

      - name: "Publish test results"
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: results.xml